### ISSUE TITLE
Separate packaging of htt and examples

### ISSUE THREAD

**Issue by palmskog** [imdea-software/htt#21]
I think most projects that use HTT can be expected to only use the framework parts (`htt` directory), as opposed to the examples. And while compiling `htt` takes a few seconds, `examples` seems to take around 3 minutes on a reasonably modern machine.

So to make it easier to depend on `htt` in a lightweight way, how about splitting off the examples into a separate `coq-htt-examples` package? Each package would be served from the same archive/release, but users can choose whether they want examples or not.

As one example, I split up the library and the tactic in [Stalmarck](https://github.com/coq-community/stalmarck) with Dune.

**Comment by clayrat** [comment]
@palmskog One challenge in implementing things like that is the fact that we want the CI to check both the core framework and examples. We're thinking to have 2 opamfiles instead: `coq-htt` would be just the core part released on OPAM, and `coq-htt-examples` would reference the whole development and be fed to CI but not released. Do you think this makes sense?

**Comment by palmskog** [comment]
@clayrat yes, having two opam files would be the ideal. However, it would also be nice if both packages based on the opam files were added to the Coq opam archive for each release (in case someone wants to depend on them). Nevertheless, for me personally and specifically for Disel, just having a lean `coq-htt` package would be great.
